apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: checkout
    dt.owner: otel-demo
  annotations:
    dt.owner: "otel-demo"
    resource-optimization.dynatrace.com/enabled: "true"
    resource-optimization.dynatrace.com/github-repo: "github.com/henrikrexed/K8s-autoscalingWorkshop"
    resource-optimization.dynatrace.com/github-rep: "github.com/henrikrexed/K8s-autoscalingWorkshop"
    resource-optimization.dynatrace.com/github-path: "otel-demo-light/checkout.yaml"
    resource-optimization.dynatrace.com/github-branch: "main"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
        dt.owner: otel-demo
      annotations:
        dt.owner: "otel-demo"
        resource-optimization.dynatrace.com/enabled: "true"
        resource-optimization.dynatrace.com/github-repo: "github.com/henrikrexed/K8s-autoscalingWorkshop"
        resource-optimization.dynatrace.com/github-rep: "github.com/henrikrexed/K8s-autoscalingWorkshop"
        resource-optimization.dynatrace.com/github-path: "otel-demo-light/checkout.yaml"
        resource-optimization.dynatrace.com/github-branch: "main"
    spec:
      containers:
        - name: checkout
          image: ghcr.io/henrikrexed/opentelemetry-demo-light/checkout:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: shared-env
          env:
            - name: OTEL_SERVICE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: shared-env
                  key: OTEL_SERVICE_PREFIX
                  optional: true
            - name: OTEL_SERVICE_NAME
              value: "$(OTEL_SERVICE_PREFIX)checkout"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=otel-demo"
            - name: POSTGRES_DB
              value: checkout_orders
          resources:
            limits:
              memory: 50Mi
            requests:
              memory: 25Mi
          readinessProbe:
            exec:
              command: ["/app/grpc_health_probe", "-addr=localhost:5050"]
            initialDelaySeconds: 10
            periodSeconds: 5
