apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  labels:
    app: product-catalog
    dt.owner: otel-demo
spec:
  selector:
    app: product-catalog
  ports:
    - port: 3550
      targetPort: 3550
