apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  labels:
    app: product-catalog
    dt.owner: otel-demo
  annotations:
    dt.owner: "otel-demo"
    resource-optimization.dynatrace.com/enabled: "true"
    resource-optimization.dynatrace.com/github-repo: "github.com/henrikrexed/K8s-autoscalingWorkshop"
    resource-optimization.dynatrace.com/github-rep: "github.com/henrikrexed/K8s-autoscalingWorkshop"
    resource-optimization.dynatrace.com/github-path: "otel-demo-light/product-catalog.yaml"
    resource-optimization.dynatrace.com/github-branch: "main"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
        dt.owner: otel-demo
      annotations:
        dt.owner: "otel-demo"
        resource-optimization.dynatrace.com/enabled: "true"
        resource-optimization.dynatrace.com/github-repo: "github.com/henrikrexed/K8s-autoscalingWorkshop"
        resource-optimization.dynatrace.com/github-rep: "github.com/henrikrexed/K8s-autoscalingWorkshop"
        resource-optimization.dynatrace.com/github-path: "otel-demo-light/product-catalog.yaml"
        resource-optimization.dynatrace.com/github-branch: "main"
    spec:
      containers:
        - name: product-catalog
          image: otel-demo-light/product-catalog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3550
          envFrom:
            - configMapRef:
                name: shared-env
          env:
            - name: OTEL_SERVICE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: shared-env
                  key: OTEL_SERVICE_PREFIX
                  optional: true
            - name: OTEL_SERVICE_NAME
              value: "$(OTEL_SERVICE_PREFIX)product-catalog"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=otel-demo"
            - name: POSTGRES_DB
              value: product_catalog
          resources:
            limits:
              memory: 20Mi
            requests:
              memory: 10Mi
          readinessProbe:
            exec:
              command: ["/app/grpc_health_probe", "-addr=localhost:3550"]
            initialDelaySeconds: 5
            periodSeconds: 5
